image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

stages:
  - build
  - docker-build

build:
  stage: build
  image: node:14.18
  script:
    - echo "Start building App"
    - npm install
    - npm run build
    - echo "Build successfully!"
  artifacts:
    expire_in: 1 hour
    paths:
      - build
      - node_modules/
  tags:
    - docker

docker-build:
  stage: docker-build
  image: docker:latest
  before_script:
    - echo $CI_REGISTRY_USER
    - echo $CI_REGISTRY
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t $CI_REGISTRY_IMAGE/aspin-meeting-rooms:latest .
    - docker push $CI_REGISTRY_IMAGE/aspin-meeting-rooms:latest
  tags:
    - docker